import { Product, Partner, Material, LiveProject, MajorPartner } from './types';

export const PARTNERS: Partner[] = [
  { name: 'Pertamina', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Pertamina_Logo.svg' },
  { name: 'Alfamart', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/ALFAMART_LOGO_BARU.png' },
  { name: 'Bridgestone', logo: 'https://bpando.org/wp-content/uploads/New-Bridgestone-Logo-Design-2011-BPO.jpg' },
  { name: 'Shell', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e8/Shell_logo.svg' },
  { name: 'Hankook', logo: 'https://1000logos.net/wp-content/uploads/2020/08/Hankook-Logo-1990s.png' },
  { name: 'Superindo', logo: 'https://www.superindo.co.id/korporasi-keberlanjutan/upload/images/LOGO%20SUPER%20INDO%20PNG.PNG' },
  { name: 'Dan+Dan', logo: 'https://e7.pngegg.com/pngimages/235/773/png-clipart-logo-indonesia-alfamart-service-health-and-beauty-miscellaneous-blue.png' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Seragam Waralaba',
    category: 'Waralaba',
    image: 'https://preloved.co.id/_ipx/w_800,f_webp,q_80,fit_cover/https://assets.preloved.co.id/products/823359/f5ea45e8-d71c-4baa-958a-ee50df281177.jpg',
    images: ['https://img.lazcdn.com/collect/social-img/85dd51c56e434efe9c627904cc8227ac_fe92ea0cfba24a3a86383bf878883974.png_720x720q80.png', 'https://sintesakonveksi.com/info/wp-content/uploads/2025/02/seragam-alfamart-2-1024x604-1.jpg', 'https://sintesakonveksi.com/info/wp-content/uploads/2025/02/seragam-alfamart-terbaru.jpg'],
    badge: 'Best Seller',
    description: 'Produk seragam unggulan kami, yang hampir seluruhnya berjenis kemeja & polo shirt. Untuk kebutuhan seragam Waralaba anda yang bergerak dibidan barang atau jasa.',
    features: ['Kualitas Premium', 'Nyaman Dipakai', 'Desain Custom'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '2',
    name: 'Seragam Otomotif',
    category: 'Otomotif',
    image: '/BRAND-PARAHITA-BG-WHITE0103_5-1024x1024.jpg',
    images: ['/BRAND-PARAHITA-BG-WHITE0113_3-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE0104_1-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE0103_5-1024x1024.jpg'],
    badge: 'Durable',
    description: 'Kami siap membantu anda dalam pembuatan seragam Otomotif dengan berbagai jenis model & desain. Yang dimana dalam pemakaiannya menuntut kualitas , daya tahan & kenyamanan.',
    features: ['Tahan Lama', 'Kualitas Tinggi', 'Desain Sporty'],
    materialId: '2',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '3',
    name: 'Seragam Tambang',
    category: 'Tambang',
    image: '/images-1.jpeg',
    images: ['/images-1.jpeg', '/images-2.jpeg', '/product-2.jpg'],
    badge: 'Safety First',
    description: 'Seragam lapangan untuk perusahaan minyak bumi, konstruksi & pekerjaan umum yang selalu kami kembangkan agar terlihat menarik, tanpa mengurangi fungsinya sebagai seragam lapangan.',
    features: ['Reflective Tape', 'Bahan Kuat', 'Fungsional'],
    materialId: '2',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: '4',
    name: 'Seragam Media',
    category: 'Media',
    image: '/images.jpeg',
    images: ['/images.jpeg', '/product-1.jpg', '/images-1.jpeg'],
    badge: 'Professional',
    description: 'Kami juga berpengalaman dalam pembuatan seragam untuk Media Elektronik & Media Cetak dengan jaminan mutu & kualitas.',
    features: ['Tampilan Elegan', 'Bahan Berkualitas', 'Jaminan Mutu'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '5',
    name: 'Seragam F&B',
    category: 'Food & Beverage',
    image: '/product-2.jpg',
    images: ['/product-2.jpg', '/images-2.jpeg', '/images.jpeg'],
    badge: 'Hygienic',
    description: 'Untuk pembuatan seragam seperti Apron, Baju & Topi Koki untuk keperluan perusahaan F&B anda, kami pun siap membantu.',
    features: ['Mudah Dibersihkan', 'Bahan Nyaman', 'Set Lengkap'],
    materialId: '1',
    sizes: ['All Size', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '6',
    name: 'Seragam Event',
    category: 'Event',
    image: '/BRAND-PARAHITA-BG-WHITE0859_5-1024x1024.jpg',
    images: ['/BRAND-PARAHITA-BG-WHITE0860_1-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE0872_3-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE0859_5-1024x1024.jpg'],
    badge: 'Fast Production',
    description: 'Perusahaan anda membutuhkan seragam untuk keperluan Gathering & Promosi yang di tuntun cepat & berkualitas? Parahita dapat membantu anda.',
    features: ['Produksi Cepat', 'Harga Kompetitif', 'Desain Menarik'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '7',
    name: 'Seragam Kantor',
    category: 'Kantor',
    image: '/BRAND-PARAHITA-BG-WHITE-_0-19_5-1024x1024.jpg',
    images: ['/BRAND-PARAHITA-BG-WHITE-_0-35_3-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE-_0-23_1-1024x1024.jpg', '/BRAND-PARAHITA-BG-WHITE-_0-19_5-1024x1024.jpg'],
    badge: 'Exclusive',
    description: 'Formal, Exclusive, & Nyaman adalah salah satu syarat seragam Kantor atau Staff dalam perusahaan anda? Kami berpengalaman dalam pembuatannya.',
    features: ['Formal & Eksklusif', 'Bahan Premium', 'Jahitan Rapi'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
  },
  {
    id: '8',
    name: 'Merchandise',
    category: 'Merchandise',
    image: '/images-1.jpeg',
    images: ['/images-1.jpeg', '/product-2.jpg', '/images-2.jpeg'],
    badge: 'Accessories',
    description: 'Accessories seperti Topi dan Goodie bag, adalah salah satu dari sekian banyak produk yang dapat kami produksi.',
    features: ['Custom Logo', 'Berbagai Pilihan', 'Kualitas Terjamin'],
    materialId: '1',
    sizes: ['All Size'],
  },
];

export const MATERIALS: Material[] = [
  {
    id: '1',
    name: 'Premium Cotton Pique',
    image: '/images.jpeg',
    specifications: {
      grammage: '230g',
      composition: '100% Cotton',
      recommendedUse: 'Uniforms & Polo Shirts',
      technicals: ['Breathable', 'Soft Touch', 'Durable Color'],
    },
  },
  {
    id: '2',
    name: 'Heavy Duty Drill',
    image: '/product-1.jpg',
    specifications: {
      grammage: '280g',
      composition: '65% Poly, 35% Cotton',
      recommendedUse: 'Safety Wear & Field Uniforms',
      technicals: ['Tear Resistant', 'Easy Care', 'Industrial Wash'],
    },
  },
  {
    id: '3',
    name: 'Lacoste CVC',
    image: '/images-1.jpeg',
    specifications: {
      grammage: '210g',
      composition: '60% Cotton, 40% Polyester',
      recommendedUse: 'Premium Polo Shirts',
      technicals: ['Absorbent', 'Shape Retention', 'Less Wrinkle'],
    },
  },
  {
    id: '4',
    name: 'Oxford Tropical',
    image: '/images.jpeg',
    specifications: {
      grammage: '180g',
      composition: 'Polyester Cotton Blend',
      recommendedUse: 'Formal Office Shirts',
      technicals: ['Cool Feel', 'Formal Look', 'Easy Iron'],
    },
  },
];

export const HERO_IMAGES = [
  '/product-1.jpg',
  '/product-2.jpg',
];

export const LIVE_PROJECTS: LiveProject[] = [
  {
    id: '1',
    title: 'Pattern Cutting',
    status: 'Sewing 75k complete',
    progress: 75,
    image: '/images.jpeg',
  },
  {
    id: '2',
    title: 'Sewing & Assembly',
    status: 'Sewing 75% complete',
    progress: 98,
    image: '/images-1.jpeg',
  },
  {
    id: '3',
    title: 'Quality Control & Finishing',
    status: 'Quality 70k complete',
    progress: 55,
    image: '/images-2.jpeg',
  },
];

export const MAJOR_PARTNERS: MajorPartner[] = [
  {
    id: '1',
    name: 'Alfamart',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/ALFAMART_LOGO_BARU.png',
    status: 'Live Order',
    progress: 85,
  },
  {
    id: '2',
    name: 'Hankook',
    logo: 'https://1000logos.net/wp-content/uploads/2020/08/Hankook-Logo-1990s.png',
    status: 'Live Order',
    progress: 60,
  },
  {
    id: '3',
    name: 'Dan+Dan',
    logo: 'https://e7.pngegg.com/pngimages/235/773/png-clipart-logo-indonesia-alfamart-service-health-and-beauty-miscellaneous-blue.png',
    status: 'Live Order',
    progress: 45,
  },
  {
    id: '4',
    name: 'Bridgestone',
    logo: 'https://bpando.org/wp-content/uploads/New-Bridgestone-Logo-Design-2011-BPO.jpg',
    status: 'Live Order',
    progress: 90,
  },
];
