import { Product, Partner, Material, LiveProject, MajorPartner } from './types';

export const PARTNERS: Partner[] = [
  { name: 'Pertamina', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Pertamina_Logo.svg' },
  { name: 'Alfamart', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/ALFAMART_LOGO_BARU.png' },
  { name: 'Bridgestone', logo: 'https://bpando.org/wp-content/uploads/New-Bridgestone-Logo-Design-2011-BPO.jpg' },
  { name: 'Shell', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e8/Shell_logo.svg' },
  { name: 'Hankook', logo: 'https://1000logos.net/wp-content/uploads/2020/08/Hankook-Logo-1990s.png' },
  { name: 'Superindo', logo: 'https://www.superindo.co.id/korporasi-keberlanjutan/upload/images/LOGO%20SUPER%20INDO%20PNG.PNG' },
  { name: 'Dan+Dan', logo: 'https://e7.pngegg.com/pngimages/235/773/png-clipart-logo-indonesia-alfamart-service-health-and-beauty-miscellaneous-blue.png' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Seragam Waralaba',
    category: 'Waralaba',
    image: '/alfa3.webp',
    images: ['/alfa1.webp', '/alfa2.webp', '/alfa3.webp'],
    badge: 'Best Seller',
    description: 'Produk seragam unggulan kami, yang hampir seluruhnya berjenis kemeja & polo shirt. Untuk kebutuhan seragam Waralaba anda yang bergerak dibidan barang atau jasa.',
    features: ['Kualitas Premium', 'Nyaman Dipakai', 'Desain Custom'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '2',
    name: 'Seragam Otomotif',
    category: 'Otomotif',
    image: '/shell.webp',
    images: ['/shell1.webp', '/shell2.webp', '/shell.webp'],
    badge: 'Durable',
    description: 'Kami siap membantu anda dalam pembuatan seragam Otomotif dengan berbagai jenis model & desain. Yang dimana dalam pemakaiannya menuntut kualitas , daya tahan & kenyamanan.',
    features: ['Tahan Lama', 'Kualitas Tinggi', 'Desain Sporty'],
    materialId: '2',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '3',
    name: 'Seragam Tambang',
    category: 'Tambang',
    image: '/pertamina1.webp',
    images: ['/pertamina2.webp', '/pertamina1.webp', '/pertamina3.webp'],
    badge: 'Safety First',
    description: 'Seragam lapangan untuk perusahaan minyak bumi, konstruksi & pekerjaan umum yang selalu kami kembangkan agar terlihat menarik, tanpa mengurangi fungsinya sebagai seragam lapangan.',
    features: ['Reflective Tape', 'Bahan Kuat', 'Fungsional'],
    materialId: '2',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: '4',
    name: 'Seragam Konstruksi & Proyek',
    category: 'Konstruksi & Proyek',
    image: '/waskita.webp',
    images: ['/waskita0.webp', '/waskita1.webp', '/waskita2.webp'],
    badge: 'Heavy Duty',
    description: 'Kami juga berpengalaman dalam pembuatan seragam untuk Konstruksi & Proyek dengan jaminan mutu & kualitas.',
    features: ['Tampilan Elegan', 'Bahan Berkualitas', 'Jaminan Mutu'],
    materialId: '2',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: '5',
    name: 'Seragam F&B',
    category: 'Food & Beverage',
    image: '/langham3.webp',
    images: ['/langham1.webp', '/langham2.webp', '/langham3.webp'],
    badge: 'Hygienic',
    description: 'Untuk pembuatan seragam seperti Apron, Baju & Topi Koki untuk keperluan perusahaan F&B anda, kami pun siap membantu.',
    features: ['Mudah Dibersihkan', 'Bahan Nyaman', 'Set Lengkap'],
    materialId: '1',
    sizes: ['All Size', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '6',
    name: 'Seragam Event',
    category: 'Event',
    image: '/dandan.webp',
    images: ['/dandan1.webp', '/dandan2.webp', '/dandan.webp'],
    badge: 'Fast Production',
    description: 'Perusahaan anda membutuhkan seragam untuk keperluan Gathering & Promosi yang di tuntun cepat & berkualitas? Parahita dapat membantu anda.',
    features: ['Produksi Cepat', 'Harga Kompetitif', 'Desain Menarik'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '7',
    name: 'Seragam Kantor',
    category: 'Kantor',
    image: '/transmart.webp',
    images: ['/transmart1.webp', '/transmart2.webp', '/transmart.webp'],
    badge: 'Exclusive',
    description: 'Formal, Exclusive, & Nyaman adalah salah satu syarat seragam Kantor atau Staff dalam perusahaan anda? Kami berpengalaman dalam pembuatannya.',
    features: ['Formal & Eksklusif', 'Bahan Premium', 'Jahitan Rapi'],
    materialId: '1',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
  },
  {
    id: '8',
    name: 'Merchandise',
    category: 'Merchandise',
    image: '/bd.webp',
    images: ['/bg.webp', '/tb.webp'],
    badge: 'Accessories',
    description: 'Accessories seperti Topi dan Goodie bag, adalah salah satu dari sekian banyak produk yang dapat kami produksi.',
    features: ['Custom Logo', 'Berbagai Pilihan', 'Kualitas Terjamin'],
    materialId: '1',
    sizes: ['All Size'],
  },
];

export const MATERIALS: Material[] = [
  {
    id: '1',
    name: 'Premium Cotton Pique',
    image: '/images.webp',
    specifications: {
      grammage: '230g',
      composition: '100% Cotton',
      recommendedUse: 'Uniforms & Polo Shirts',
      technicals: ['Breathable', 'Soft Touch', 'Durable Color'],
    },
  },
  {
    id: '2',
    name: 'Heavy Duty Drill',
    image: '/product-1.webp',
    specifications: {
      grammage: '280g',
      composition: '65% Poly, 35% Cotton',
      recommendedUse: 'Safety Wear & Field Uniforms',
      technicals: ['Tear Resistant', 'Easy Care', 'Industrial Wash'],
    },
  },
  {
    id: '3',
    name: 'Lacoste CVC',
    image: '/images-1.webp',
    specifications: {
      grammage: '210g',
      composition: '60% Cotton, 40% Polyester',
      recommendedUse: 'Premium Polo Shirts',
      technicals: ['Absorbent', 'Shape Retention', 'Less Wrinkle'],
    },
  },
  {
    id: '4',
    name: 'Oxford Tropical',
    image: '/images.webp',
    specifications: {
      grammage: '180g',
      composition: 'Polyester Cotton Blend',
      recommendedUse: 'Formal Office Shirts',
      technicals: ['Cool Feel', 'Formal Look', 'Easy Iron'],
    },
  },
];

export const HERO_IMAGES = [
  '/Parahitaprimasentosa.webp',
  '/product-1.webp',
];

export const LIVE_PROJECTS: LiveProject[] = [
  {
    id: '1',
    title: 'Pattern Cutting',
    status: 'Sewing 75k complete',
    progress: 75,
    image: '/images.webp',
  },
  {
    id: '2',
    title: 'Sewing & Assembly',
    status: 'Sewing 75% complete',
    progress: 98,
    image: '/images-1.webp',
  },
  {
    id: '3',
    title: 'Quality Control & Finishing',
    status: 'Quality 70k complete',
    progress: 55,
    image: '/images-2.webp',
  },
];

export const MAJOR_PARTNERS: MajorPartner[] = [
  {
    id: '1',
    name: 'Alfamart',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/ALFAMART_LOGO_BARU.png',
    status: 'Live Order',
    progress: 85,
  },
  {
    id: '2',
    name: 'Shell',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e8/Shell_logo.svg',
    status: 'Live Order',
    progress: 60,
  },
  {
    id: '3',
    name: 'Dan+Dan',
    logo: 'https://e7.pngegg.com/pngimages/235/773/png-clipart-logo-indonesia-alfamart-service-health-and-beauty-miscellaneous-blue.png',
    status: 'Live Order',
    progress: 45,
  },
  {
    id: '4',
    name: 'Bridgestone',
    logo: 'https://bpando.org/wp-content/uploads/New-Bridgestone-Logo-Design-2011-BPO.jpg',
    status: 'Live Order',
    progress: 90,
  },
  {
    id: '5',
    name: 'Hankook',
    logo: 'https://1000logos.net/wp-content/uploads/2020/08/Hankook-Logo-1990s.png',
    status: 'Live Order',
    progress: 90,
  },
  {
    id: '6',
    name: 'Pertamina',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Pertamina_Logo.svg',
    status: 'Live Order',
    progress: 90,
  },
  {
    id: '7',
    name: 'Superindo',
    logo: 'https://www.superindo.co.id/korporasi-keberlanjutan/upload/images/LOGO%20SUPER%20INDO%20PNG.PNG',
    status: 'Live Order',
    progress: 90,
  },
];
